#!/bin/bash
CONFIGFILE="/usr/local/src/klipper-moonraker-usb-autoconnect/klipper_usb_autoconnect.conf"

if [ ! -f ${CONFIGFILE} ]; then
    echo "Configuration file \"${CONFIGFILE}\""
    exit 1
fi

# Load config file
. ${CONFIGFILE}

# Send POST request to reconnect serial connection
curl -X POST http://${HOST}:${PORT}/printer/firmware_restart
